#!/bin/bash

ARDUINO_INSTALL_PATH="/Users/`whoami`/Dropbox/Arduino"


ARDUINO_HARDWARE="Framework"
ARDUINO_LIBRARIES="Libraries"
ARDUINO_EXAMPLES="Examples"

USER_LIBRARIES="Libraries"

DOWNLOAD_DIRECTORY="downloads"
ARDUINO_DOWNLOAD_PATH="http://arduino.googlecode.com/files/arduino-1.0.5-macosx.zip"
#ARDUINO_DOWNLOAD_PATH="https://raw.github.com/ikiselev/ArduinoFrameworkFetch/master/README.md"

ARDUINO_APP_NAME="Arduino.app"
ARDUINO_RESOURCES="Contents/Resources/Java"

ARDUINO_HARDWARE_PATH="${ARDUINO_APP_NAME}/${ARDUINO_RESOURCES}/hardware/arduino"
ARDUINO_LIBRARIES_PATH="${ARDUINO_APP_NAME}/${ARDUINO_RESOURCES}/libraries"
ARDUINO_EXAMPLES_PATH="${ARDUINO_APP_NAME}/${ARDUINO_RESOURCES}/examples"


EXCLUDE="${ARDUINO_HARDWARE_PATH}/firmwares/wifishield*"

if [ ! -d $ARDUINO_INSTALL_PATH ]
then
	echo Make sure directory exists you are installing at ${ARDUINO_INSTALL_PATH}
	exit
fi

if [ ! -d ${ARDUINO_INSTALL_PATH}/${USER_LIBRARIES} ]; then mkdir ${ARDUINO_INSTALL_PATH}/${USER_LIBRARIES}; fi
if [ ! -d ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE} ]; then mkdir ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}; fi
if [ ! -d ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES} ]; then mkdir ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES}; fi
if [ ! -d ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES} ]; then mkdir ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES}; fi

if [ ! -d $DOWNLOAD_DIRECTORY ]; then mkdir $DOWNLOAD_DIRECTORY; fi


ARDUINO_FILENAME=${DOWNLOAD_DIRECTORY}/`basename $ARDUINO_DOWNLOAD_PATH`
echo Checking for ${ARDUINO_FILENAME}

if [ ! -f $ARDUINO_FILENAME ]
then
	echo File does not exist, downloading
	`curl ${ARDUINO_DOWNLOAD_PATH} -o ${ARDUINO_FILENAME}`
else
	echo File exists
fi

echo "Installing..."


# Clean
rm -rf ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/*
#rm -rf ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES}/*
rm -rf ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES}/*

#Install hardware path without excludes dir
unzip ${ARDUINO_FILENAME} ${ARDUINO_HARDWARE_PATH}/* -d ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE} -x ${EXCLUDE} >> /dev/null
mv -f ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_HARDWARE_PATH}/* ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/
rm -rf ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_APP_NAME}


#Install libraries
unzip ${ARDUINO_FILENAME} ${ARDUINO_LIBRARIES_PATH}/* -d ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES} >> /dev/null
mv -f ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES}/${ARDUINO_LIBRARIES_PATH}/* ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES}/
rm -rf ${ARDUINO_INSTALL_PATH}/${ARDUINO_HARDWARE}/${ARDUINO_LIBRARIES}/${ARDUINO_APP_NAME}

#Install examples
unzip ${ARDUINO_FILENAME} ${ARDUINO_EXAMPLES_PATH}/* -d ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES} >> /dev/null
mv -f ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES}/${ARDUINO_EXAMPLES_PATH}/* ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES}/
rm -rf ${ARDUINO_INSTALL_PATH}/${ARDUINO_EXAMPLES}/${ARDUINO_APP_NAME}


echo "Ok"
